server:
  port: 8080

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/practice
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml

logging:
  config: classpath:log4j2.xml